---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: uninstall webserver  on ubuntu ansible nodes
    apt: 
      name: apache2
      state: absent
    when: ansible_os_family =="Debian"