---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver  on ubuntu ansible nodes
    apt: 
      name={{ubuntuwebservername}}
      update_cache=yes 
      state=latest